name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'docs'
      - 'dependencies'
  default: patch

categories:
  - title: 'Breaking Changes'
    labels:
      - 'major'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'docs'
  - title: 'Dependencies'
    labels:
      - 'dependencies'
  - title: 'Testing'
    labels:
      - 'test'
  - title: 'Performance'
    labels:
      - 'performance'

exclude-labels:
  - 'skip-changelog'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
