version: 2
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/confd
    binary: confd
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.GitSHA={{ .ShortCommit }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
archives:
  - name_template: '{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    formats: [tar.gz]
    format_overrides:
    - goos: windows
      formats: [zip]
    files:
    - none*
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  version_template: "{{ .Tag }}-dev"
changelog:
  disable: true

release:
  prerelease: auto

dockers_v2:
  - images:
      - "abtreece/confd"
      - "ghcr.io/abtreece/confd"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: docker/Dockerfile
    tags:
      - "{{ .Tag }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    labels:
      org.opencontainers.image.title: confd
      org.opencontainers.image.description: Lightweight configuration management tool
      org.opencontainers.image.url: https://github.com/abtreece/confd
      org.opencontainers.image.source: https://github.com/abtreece/confd
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: MIT